# Form implementation generated from reading ui file 'ui\test1.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import json
from urllib.request import urlopen
from PyQt6 import QtCore, QtGui, QtWidgets
import requests


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(140, 70, 221, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 150, 221, 31))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 80, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(150, 240, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        
        self.lineEdit.textChanged.connect(self.login)
        self.lineEdit_2.textChanged.connect(self.password)
        
        
        self.pushButton.clicked.connect(self.pushBatton_was_clicked)
        
        
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Login"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.pushButton.setText(_translate("Dialog", "Log in"))
        
    
        
        
    def login(self, login):
        self.login = str(login)
        
    def password(self, passw):
        self.password = str(passw)
        
    def pushBatton_was_clicked(self):
        url_login = 'http://127.0.0.1:8000/auth/token/login'
        keys_login = {"username": self.login,
                "password": self.password}
        try:
            req_login = requests.post(url_login, data=keys_login)
        
            if str(req_login) == "<Response [200]>":
                token = json.loads(req_login.text)["auth_token"]
            
                url_profile_information = "http://127.0.0.1:8000/api/v1/auth/users/me"
                keys_profile_information = {
                    "Authorization": "Token " + token
                }

                req_profile_inf = requests.get(url_profile_information, headers=keys_profile_information)
            
                print(req_profile_inf.text)
            else:
                print("login or password is incorrect")
        except requests.exceptions.ConnectionError:
            print("Проверьте доступ к интернету")
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
