# Form implementation generated from reading ui file 'UI\Dialog_saved_games.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_saved_games(object):
    def setupUi(self, Dialog_saved_games):
        Dialog_saved_games.setObjectName("Dialog_saved_games")
        Dialog_saved_games.resize(650, 700)
        Dialog_saved_games.setMinimumSize(QtCore.QSize(650, 700))
        Dialog_saved_games.setMaximumSize(QtCore.QSize(650, 700))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Dialog_saved_games.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI\\../../../../../Pictures/Лого_u2p/vector (svg)/icon_logo.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog_saved_games.setWindowIcon(icon)
        Dialog_saved_games.setStyleSheet("background:#fff;")
        Dialog_saved_games.setSizeGripEnabled(False)
        Dialog_saved_games.setModal(False)
        self.frame_saved_games = QtWidgets.QFrame(Dialog_saved_games)
        self.frame_saved_games.setGeometry(QtCore.QRect(16, 60, 618, 558))
        self.frame_saved_games.setStyleSheet("border-radius: 20px;\n"
"background:#DCDCDC;")
        self.frame_saved_games.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_saved_games.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_saved_games.setObjectName("frame_saved_games")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_saved_games)
        self.tableWidget.setGeometry(QtCore.QRect(16, 16, 585, 526))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("QTableView {\n"
"    font: 81 16pt \"Montserrat ExtraBold\";\n"
"    selection-background-color: rgba(255, 255, 255, 0);\n"
"    color:#000;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    color:#000;\n"
"border: 1px solid #000;\n"
"font: 81 16pt \"Montserrat ExtraBold\";\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item {\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
" QScrollBar:vertical {\n"
"     background:  rgba(0, 0, 0, 0);\n"
"     border-top-right-radius: 4px;\n"
"     border-bottom-right-radius: 4px;\n"
"     width: 12px;\n"
"     margin: 0px;\n"
"}\n"
"\n"
" QScrollBar::handle:vertical {\n"
"    background-color: black;\n"
"     border-radius: 4px;\n"
"     min-height: 20px;\n"
"     margin: 0px 2px 0px 2px;\n"
" }\n"
"")
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.tableWidget.setIconSize(QtCore.QSize(20, 22))
        self.tableWidget.setTextElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerItem)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(15)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        item.setIcon(icon)
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        item.setIcon(icon)
        self.tableWidget.setItem(1, 4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.label_chose_one_saved_game = QtWidgets.QLabel(Dialog_saved_games)
        self.label_chose_one_saved_game.setGeometry(QtCore.QRect(0, 0, 650, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_chose_one_saved_game.setFont(font)
        self.label_chose_one_saved_game.setStyleSheet("color:#000;\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_chose_one_saved_game.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_chose_one_saved_game.setObjectName("label_chose_one_saved_game")
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog_saved_games)
        self.pushButton_cancel.setGeometry(QtCore.QRect(182, 628, 271, 62))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_cancel.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"border: 3px solid rgba(239, 0, 9, 1);\n"
"color: rgb(0, 0, 0);\n"
"padding-top: -1px;\n"
"\n"
"font-family: Montserrat ExtraBold;\n"
"font-size: 20px;\n"
"font-style: normal;\n"
"font-weight: 800;\n"
"line-height: 24px;\n"
"letter-spacing: -1px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"border-radius: 5px;\n"
"border: 3px solid rgba(47, 47, 47, 1);\n"
"color: #fff;\n"
"padding-top: -1px;\n"
"background-color:rgba(239, 0, 9, 1);\n"
"}")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        
        
        #connections
        self.pushButton_cancel.clicked.connect(Dialog_saved_games.reject)

        self.retranslateUi(Dialog_saved_games)
        QtCore.QMetaObject.connectSlotsByName(Dialog_saved_games)

    def retranslateUi(self, Dialog_saved_games):
        _translate = QtCore.QCoreApplication.translate
        Dialog_saved_games.setWindowTitle(_translate("Dialog_saved_games", "U2P Simulator - Saved Games"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog_saved_games", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog_saved_games", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog_saved_games", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog_saved_games", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_saved_games", "Название"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_saved_games", "Дата сохраненения"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_saved_games", "Период"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Dialog_saved_games", "asdasdas"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Dialog_saved_games", "dsadasdasd <a>sdasd</a>"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Dialog_saved_games", "12"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_chose_one_saved_game.setText(_translate("Dialog_saved_games", "Выберете сохраненную игру"))
        self.pushButton_cancel.setText(_translate("Dialog_saved_games", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_saved_games = QtWidgets.QDialog()
    ui = Ui_Dialog_saved_games()
    ui.setupUi(Dialog_saved_games)
    Dialog_saved_games.show()
    sys.exit(app.exec())
