
## by karton4ik

from PyQt6 import QtCore, QtGui, QtWidgets
import ast

class Ui_Dialog_setParameters(object):
    def setupUi(self, Dialog_setParameters):
        self.file = ast.literal_eval(open("settings.txt", "r").readline())
        Dialog_setParameters.setObjectName("Dialog_setParameters")
        Dialog_setParameters.setEnabled(True)
        Dialog_setParameters.resize(500, 380)
        Dialog_setParameters.setMinimumSize(QtCore.QSize(500, 380))
        Dialog_setParameters.setMaximumSize(QtCore.QSize(500, 380))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/setting.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog_setParameters.setWindowIcon(icon)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 111, 111))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 111, 111))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 111, 111))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 111, 111))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 111, 111))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 111, 111))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipText, brush)
        Dialog_setParameters.setPalette(palette)
        Dialog_setParameters.setStatusTip("")
        Dialog_setParameters.setWhatsThis("")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_setParameters)
        self.buttonBox.setGeometry(QtCore.QRect(290, 325, 161, 32))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.label_Sensitivity = QtWidgets.QLabel(Dialog_setParameters)
        self.label_Sensitivity.setGeometry(QtCore.QRect(210, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.label_Sensitivity.setFont(font)
        self.label_Sensitivity.setObjectName("label_Sensitivity")
        self.horizontalScrollBar_DemandChange = QtWidgets.QScrollBar(Dialog_setParameters)
        self.horizontalScrollBar_DemandChange.setGeometry(QtCore.QRect(40, 70, 181, 16))
        self.horizontalScrollBar_DemandChange.setMinimum(-50)
        self.horizontalScrollBar_DemandChange.setMaximum(50)
        self.horizontalScrollBar_DemandChange.setPageStep(10)
        self.horizontalScrollBar_DemandChange.setProperty("value", 0)
        self.horizontalScrollBar_DemandChange.setSliderPosition(self.file["DemandChange"])
        self.horizontalScrollBar_DemandChange.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalScrollBar_DemandChange.setInvertedAppearance(False)
        self.horizontalScrollBar_DemandChange.setObjectName("horizontalScrollBar_DemandChange")
        
        self.horizontalScrollBar_RandDImpact = QtWidgets.QScrollBar(Dialog_setParameters)
        self.horizontalScrollBar_RandDImpact.setGeometry(QtCore.QRect(270, 70, 181, 16))
        self.horizontalScrollBar_RandDImpact.setMinimum(-50)
        self.horizontalScrollBar_RandDImpact.setMaximum(50)
        self.horizontalScrollBar_RandDImpact.setPageStep(10)
        self.horizontalScrollBar_RandDImpact.setProperty("value", 0)
        self.horizontalScrollBar_RandDImpact.setSliderPosition(self.file["RandDImpact"])
        self.horizontalScrollBar_RandDImpact.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalScrollBar_RandDImpact.setInvertedAppearance(False)
        self.horizontalScrollBar_RandDImpact.setObjectName("horizontalScrollBar_RandDImpact")
        
        self.horizontalScrollBar_PriceImpact = QtWidgets.QScrollBar(Dialog_setParameters)
        self.horizontalScrollBar_PriceImpact.setGeometry(QtCore.QRect(40, 130, 181, 16))
        self.horizontalScrollBar_PriceImpact.setMinimum(-50)
        self.horizontalScrollBar_PriceImpact.setMaximum(50)
        self.horizontalScrollBar_PriceImpact.setPageStep(10)
        self.horizontalScrollBar_PriceImpact.setProperty("value", 0)
        self.horizontalScrollBar_PriceImpact.setSliderPosition(self.file["PriceImpact"])
        self.horizontalScrollBar_PriceImpact.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalScrollBar_PriceImpact.setInvertedAppearance(False)
        self.horizontalScrollBar_PriceImpact.setObjectName("horizontalScrollBar_PriceImpact")
        
        self.horizontalScrollBar_MarketingImpact = QtWidgets.QScrollBar(Dialog_setParameters)
        self.horizontalScrollBar_MarketingImpact.setGeometry(QtCore.QRect(270, 130, 181, 16))
        self.horizontalScrollBar_MarketingImpact.setMinimum(-50)
        self.horizontalScrollBar_MarketingImpact.setMaximum(50)
        self.horizontalScrollBar_MarketingImpact.setPageStep(10)
        self.horizontalScrollBar_MarketingImpact.setProperty("value", 0)
        self.horizontalScrollBar_MarketingImpact.setSliderPosition(self.file["MarketingImpact"])
        self.horizontalScrollBar_MarketingImpact.setTracking(True)
        self.horizontalScrollBar_MarketingImpact.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalScrollBar_MarketingImpact.setInvertedAppearance(False)
        self.horizontalScrollBar_MarketingImpact.setObjectName("horizontalScrollBar_MarketingImpact")
        
        
        
        self.label_DemandChange = QtWidgets.QLabel(Dialog_setParameters)
        self.label_DemandChange.setGeometry(QtCore.QRect(40, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_DemandChange.setFont(font)
        self.label_DemandChange.setObjectName("label_DemandChange")
        self.label_DemandChange_int = QtWidgets.QLabel(Dialog_setParameters)
        self.label_DemandChange_int.setGeometry(QtCore.QRect(185, 40, 38, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_DemandChange_int.setFont(font)
        self.label_DemandChange_int.setObjectName("label_DemandChange_int")
        self.label_PriceImpact_int = QtWidgets.QLabel(Dialog_setParameters)
        self.label_PriceImpact_int.setGeometry(QtCore.QRect(185, 100, 38, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_PriceImpact_int.setFont(font)
        self.label_PriceImpact_int.setObjectName("label_PriceImpact_int")
        self.label_PriceImpact = QtWidgets.QLabel(Dialog_setParameters)
        self.label_PriceImpact.setGeometry(QtCore.QRect(40, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_PriceImpact.setFont(font)
        self.label_PriceImpact.setObjectName("label_PriceImpact")
        self.label_RandDImpact_int = QtWidgets.QLabel(Dialog_setParameters)
        self.label_RandDImpact_int.setGeometry(QtCore.QRect(415, 40, 38, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_RandDImpact_int.setFont(font)
        self.label_RandDImpact_int.setObjectName("label_RandDImpact_int")
        self.label_RandDImpact = QtWidgets.QLabel(Dialog_setParameters)
        self.label_RandDImpact.setGeometry(QtCore.QRect(270, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_RandDImpact.setFont(font)
        self.label_RandDImpact.setObjectName("label_RandDImpact")
        self.label_MarketingImpact_int = QtWidgets.QLabel(Dialog_setParameters)
        self.label_MarketingImpact_int.setGeometry(QtCore.QRect(415, 100, 38, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_MarketingImpact_int.setFont(font)
        self.label_MarketingImpact_int.setObjectName("label_MarketingImpact_int")
        self.label_MarketingImpact = QtWidgets.QLabel(Dialog_setParameters)
        self.label_MarketingImpact.setGeometry(QtCore.QRect(270, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_MarketingImpact.setFont(font)
        self.label_MarketingImpact.setObjectName("label_MarketingImpact")
        self.label_General = QtWidgets.QLabel(Dialog_setParameters)
        self.label_General.setGeometry(QtCore.QRect(90, 180, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.label_General.setFont(font)
        self.label_General.setObjectName("label_General")
        self.line = QtWidgets.QFrame(Dialog_setParameters)
        self.line.setGeometry(QtCore.QRect(-10, 160, 511, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog_setParameters)
        self.line_2.setGeometry(QtCore.QRect(240, 170, 16, 241))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog_setParameters)
        self.line_3.setGeometry(QtCore.QRect(250, 290, 251, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_TaxRate = QtWidgets.QLabel(Dialog_setParameters)
        self.label_TaxRate.setGeometry(QtCore.QRect(10, 220, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_TaxRate.setFont(font)
        self.label_TaxRate.setObjectName("label_TaxRate")
        self.lineEdit_TaxRate = QtWidgets.QLineEdit(Dialog_setParameters)
        self.lineEdit_TaxRate.setGeometry(QtCore.QRect(160, 220, 60, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lineEdit_TaxRate.setFont(font)
        self.lineEdit_TaxRate.setInputMask("")
        self.lineEdit_TaxRate.setMaxLength(6)
        self.lineEdit_TaxRate.setFrame(True)
        self.lineEdit_TaxRate.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_TaxRate.setDragEnabled(False)
        self.lineEdit_TaxRate.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_TaxRate.setClearButtonEnabled(False)
        self.lineEdit_TaxRate.setObjectName("lineEdit_TaxRate")
        self.lineEdit_TaxRate.setValidator(QtGui.QIntValidator(0, 99))
        
        self.label_TaxRate_unit = QtWidgets.QLabel(Dialog_setParameters)
        self.label_TaxRate_unit.setGeometry(QtCore.QRect(222, 220, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_TaxRate_unit.setFont(font)
        self.label_TaxRate_unit.setObjectName("label_TaxRate_unit")
        self.label_InterestRate = QtWidgets.QLabel(Dialog_setParameters)
        self.label_InterestRate.setGeometry(QtCore.QRect(10, 240, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_InterestRate.setFont(font)
        self.label_InterestRate.setObjectName("label_InterestRate")    
        self.label_InterestRate_unit = QtWidgets.QLabel(Dialog_setParameters)
        self.label_InterestRate_unit.setGeometry(QtCore.QRect(222, 240, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_InterestRate_unit.setFont(font)
        self.label_InterestRate_unit.setObjectName("label_InterestRate_unit")
        self.lineEdit_InterestRate = QtWidgets.QLineEdit(Dialog_setParameters)
        self.lineEdit_InterestRate.setGeometry(QtCore.QRect(160, 240, 60, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lineEdit_InterestRate.setFont(font)
        self.lineEdit_InterestRate.setInputMask("")
        self.lineEdit_InterestRate.setMaxLength(6)
        self.lineEdit_InterestRate.setFrame(True)
        self.lineEdit_InterestRate.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_InterestRate.setDragEnabled(False)
        self.lineEdit_InterestRate.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_InterestRate.setClearButtonEnabled(False)
        self.lineEdit_InterestRate.setObjectName("lineEdit_InterestRate")
        self.lineEdit_InterestRate.setValidator(QtGui.QIntValidator(0, 99))
        
        self.label_LoanLimit = QtWidgets.QLabel(Dialog_setParameters)
        self.label_LoanLimit.setGeometry(QtCore.QRect(10, 260, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_LoanLimit.setFont(font)
        self.label_LoanLimit.setObjectName("label_LoanLimit")
        self.label_LoanLimit_unit = QtWidgets.QLabel(Dialog_setParameters)
        self.label_LoanLimit_unit.setGeometry(QtCore.QRect(222, 260, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_LoanLimit_unit.setFont(font)
        self.label_LoanLimit_unit.setObjectName("label_LoanLimit_unit")
        self.lineEdit_LoanLimit = QtWidgets.QLineEdit(Dialog_setParameters)
        self.lineEdit_LoanLimit.setGeometry(QtCore.QRect(160, 260, 60, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lineEdit_LoanLimit.setFont(font)
        self.lineEdit_LoanLimit.setInputMask("")
        self.lineEdit_LoanLimit.setMaxLength(6)
        self.lineEdit_LoanLimit.setFrame(True)
        self.lineEdit_LoanLimit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_LoanLimit.setDragEnabled(False)
        self.lineEdit_LoanLimit.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_LoanLimit.setClearButtonEnabled(False)
        self.lineEdit_LoanLimit.setObjectName("lineEdit_LoanLimit")
        self.lineEdit_LoanLimit.setValidator(QtGui.QIntValidator(0, 999999))
        
        self.label_MaxPrice = QtWidgets.QLabel(Dialog_setParameters)
        self.label_MaxPrice.setGeometry(QtCore.QRect(10, 280, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_MaxPrice.setFont(font)
        self.label_MaxPrice.setObjectName("label_MaxPrice")
        self.label_MaxPrice_unit = QtWidgets.QLabel(Dialog_setParameters)
        self.label_MaxPrice_unit.setGeometry(QtCore.QRect(222, 280, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_MaxPrice_unit.setFont(font)
        self.label_MaxPrice_unit.setObjectName("label_MaxPrice_unit")
        self.lineEdit_MaxPrice = QtWidgets.QLineEdit(Dialog_setParameters)
        self.lineEdit_MaxPrice.setGeometry(QtCore.QRect(160, 280, 60, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lineEdit_MaxPrice.setFont(font)
        self.lineEdit_MaxPrice.setInputMask("")
        self.lineEdit_MaxPrice.setMaxLength(6)
        self.lineEdit_MaxPrice.setFrame(True)
        self.lineEdit_MaxPrice.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_MaxPrice.setDragEnabled(False)
        self.lineEdit_MaxPrice.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_MaxPrice.setClearButtonEnabled(False)
        self.lineEdit_MaxPrice.setObjectName("lineEdit_MaxPrice")
        self.lineEdit_MaxPrice.setValidator(QtGui.QIntValidator(0, 9999))
        
        self.label_MaxMarketing = QtWidgets.QLabel(Dialog_setParameters)
        self.label_MaxMarketing.setGeometry(QtCore.QRect(10, 300, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_MaxMarketing.setFont(font)
        self.label_MaxMarketing.setObjectName("label_MaxMarketing")
        self.label_MaxMarketing_unit = QtWidgets.QLabel(Dialog_setParameters)
        self.label_MaxMarketing_unit.setGeometry(QtCore.QRect(222, 300, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_MaxMarketing_unit.setFont(font)
        self.label_MaxMarketing_unit.setObjectName("label_MaxMarketing_unit")
        self.lineEdit_MaxMarketing = QtWidgets.QLineEdit(Dialog_setParameters)
        self.lineEdit_MaxMarketing.setGeometry(QtCore.QRect(160, 300, 60, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lineEdit_MaxMarketing.setFont(font)
        self.lineEdit_MaxMarketing.setInputMask("")
        self.lineEdit_MaxMarketing.setMaxLength(6)
        self.lineEdit_MaxMarketing.setFrame(True)
        self.lineEdit_MaxMarketing.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_MaxMarketing.setDragEnabled(False)
        self.lineEdit_MaxMarketing.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_MaxMarketing.setClearButtonEnabled(False)
        self.lineEdit_MaxMarketing.setObjectName("lineEdit_MaxMarketing")
        self.lineEdit_MaxMarketing.setValidator(QtGui.QIntValidator(0, 999999))
        
        self.label_MaxCapInv = QtWidgets.QLabel(Dialog_setParameters)
        self.label_MaxCapInv.setGeometry(QtCore.QRect(10, 320, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_MaxCapInv.setFont(font)
        self.label_MaxCapInv.setObjectName("label_MaxCapInv")
        self.label_MaxCapInv_unit = QtWidgets.QLabel(Dialog_setParameters)
        self.label_MaxCapInv_unit.setGeometry(QtCore.QRect(222, 320, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_MaxCapInv_unit.setFont(font)
        self.label_MaxCapInv_unit.setObjectName("label_MaxCapInv_unit")
        self.lineEdit_MaxCapInv = QtWidgets.QLineEdit(Dialog_setParameters)
        self.lineEdit_MaxCapInv.setGeometry(QtCore.QRect(160, 320, 60, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lineEdit_MaxCapInv.setFont(font)
        self.lineEdit_MaxCapInv.setInputMask("")
        self.lineEdit_MaxCapInv.setMaxLength(6)
        self.lineEdit_MaxCapInv.setFrame(True)
        self.lineEdit_MaxCapInv.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_MaxCapInv.setDragEnabled(False)
        self.lineEdit_MaxCapInv.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_MaxCapInv.setClearButtonEnabled(False)
        self.lineEdit_MaxCapInv.setObjectName("lineEdit_MaxCapInv")
        self.lineEdit_MaxCapInv.setValidator(QtGui.QIntValidator(0, 999999))
        
        self.label_MaxRandD = QtWidgets.QLabel(Dialog_setParameters)
        self.label_MaxRandD.setGeometry(QtCore.QRect(10, 340, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_MaxRandD.setFont(font)
        self.label_MaxRandD.setObjectName("label_MaxRandD")
        self.label_MaxRandD_unit = QtWidgets.QLabel(Dialog_setParameters)
        self.label_MaxRandD_unit.setGeometry(QtCore.QRect(222, 340, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_MaxRandD_unit.setFont(font)
        self.label_MaxRandD_unit.setObjectName("label_MaxRandD_unit")
        self.lineEdit_MaxRandD = QtWidgets.QLineEdit(Dialog_setParameters)
        self.lineEdit_MaxRandD.setGeometry(QtCore.QRect(160, 340, 60, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lineEdit_MaxRandD.setFont(font)
        self.lineEdit_MaxRandD.setInputMask("")
        self.lineEdit_MaxRandD.setMaxLength(6)
        self.lineEdit_MaxRandD.setFrame(True)
        self.lineEdit_MaxRandD.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_MaxRandD.setDragEnabled(False)
        self.lineEdit_MaxRandD.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_MaxRandD.setClearButtonEnabled(False)
        self.lineEdit_MaxRandD.setObjectName("lineEdit_MaxRandD")
        self.lineEdit_MaxRandD.setValidator(QtGui.QIntValidator(0, 999999))
        
        self.label_RandD_unit = QtWidgets.QLabel(Dialog_setParameters)
        self.label_RandD_unit.setGeometry(QtCore.QRect(472, 260, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_RandD_unit.setFont(font)
        self.label_RandD_unit.setObjectName("label_RandD_unit")
        self.label_Price_unit = QtWidgets.QLabel(Dialog_setParameters)
        self.label_Price_unit.setGeometry(QtCore.QRect(472, 240, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_Price_unit.setFont(font)
        self.label_Price_unit.setObjectName("label_Price_unit")
        self.label_Marketing = QtWidgets.QLabel(Dialog_setParameters)
        self.label_Marketing.setGeometry(QtCore.QRect(260, 220, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_Marketing.setFont(font)
        self.label_Marketing.setObjectName("label_Marketing")
        self.label_Price = QtWidgets.QLabel(Dialog_setParameters)
        self.label_Price.setGeometry(QtCore.QRect(260, 240, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_Price.setFont(font)
        self.label_Price.setObjectName("label_Price")
        self.label_Marketing_unit = QtWidgets.QLabel(Dialog_setParameters)
        self.label_Marketing_unit.setGeometry(QtCore.QRect(472, 220, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_Marketing_unit.setFont(font)
        self.label_Marketing_unit.setObjectName("label_Marketing_unit")
        self.label_RandD = QtWidgets.QLabel(Dialog_setParameters)
        self.label_RandD.setGeometry(QtCore.QRect(260, 260, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_RandD.setFont(font)
        self.label_RandD.setObjectName("label_RandD")
        self.lineEdit_RandD = QtWidgets.QLineEdit(Dialog_setParameters)
        self.lineEdit_RandD.setGeometry(QtCore.QRect(410, 260, 60, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lineEdit_RandD.setFont(font)
        self.lineEdit_RandD.setInputMask("")
        self.lineEdit_RandD.setMaxLength(2)
        self.lineEdit_RandD.setFrame(True)
        self.lineEdit_RandD.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_RandD.setDragEnabled(False)
        self.lineEdit_RandD.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_RandD.setClearButtonEnabled(False)
        self.lineEdit_RandD.setObjectName("lineEdit_RandD")
        self.lineEdit_RandD.setValidator(QtGui.QIntValidator(0, 99))
        
        self.lineEdit_Price = QtWidgets.QLineEdit(Dialog_setParameters)
        self.lineEdit_Price.setGeometry(QtCore.QRect(410, 240, 60, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lineEdit_Price.setFont(font)
        self.lineEdit_Price.setInputMask("")
        self.lineEdit_Price.setMaxLength(2)
        self.lineEdit_Price.setFrame(True)
        self.lineEdit_Price.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_Price.setDragEnabled(False)
        self.lineEdit_Price.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_Price.setClearButtonEnabled(False)
        self.lineEdit_Price.setObjectName("lineEdit_Price")
        self.lineEdit_Price.setValidator(QtGui.QIntValidator(0, 99))
        
        self.lineEdit_Marketing = QtWidgets.QLineEdit(Dialog_setParameters)
        self.lineEdit_Marketing.setGeometry(QtCore.QRect(410, 220, 60, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lineEdit_Marketing.setFont(font)
        self.lineEdit_Marketing.setInputMask("")
        self.lineEdit_Marketing.setMaxLength(2)
        self.lineEdit_Marketing.setFrame(True)
        self.lineEdit_Marketing.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_Marketing.setDragEnabled(False)
        self.lineEdit_Marketing.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_Marketing.setClearButtonEnabled(False)
        self.lineEdit_Marketing.setObjectName("lineEdit_Marketing")
        self.lineEdit_Marketing.setValidator(QtGui.QIntValidator(0, 99))
        
        self.label_MarketShare = QtWidgets.QLabel(Dialog_setParameters)
        self.label_MarketShare.setGeometry(QtCore.QRect(320, 180, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.label_MarketShare.setFont(font)
        self.label_MarketShare.setObjectName("label_MarketShare")
        self.pushButton_ResetSettings = QtWidgets.QPushButton(Dialog_setParameters)
        self.pushButton_ResetSettings.setGeometry(QtCore.QRect(0, 0, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(7)
        self.pushButton_ResetSettings.setFont(font)
        self.pushButton_ResetSettings.setStatusTip("")
        self.pushButton_ResetSettings.setAccessibleName("")
        self.pushButton_ResetSettings.setAccessibleDescription("")
        self.pushButton_ResetSettings.setObjectName("pushButton_ResetSettings")
        
        self.label_MAX100 = QtWidgets.QLabel(Dialog_setParameters)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(8)
        self.label_MAX100.setFont(font)
        self.label_MAX100.setObjectName("label_MAX100")
        
        
        self.label_MAX100.setGeometry(QtCore.QRect(412, 207, 55, 15))

        self.retranslateUi(Dialog_setParameters)
        self.buttonBox.accepted.connect(Dialog_setParameters.accept) # type: ignore
        self.buttonBox.accepted.connect(self.save_was_clicked)
        self.buttonBox.rejected.connect(Dialog_setParameters.reject) # type: ignore
        
        self.horizontalScrollBar_DemandChange.valueChanged.connect(self.horizontalScrollBar_DemandChange_valueChanged)
        self.horizontalScrollBar_RandDImpact.valueChanged.connect(self.horizontalScrollBar_RandDImpact_valueChanged)
        self.horizontalScrollBar_PriceImpact.valueChanged.connect(self.horizontalScrollBar_PriceImpact_valueChanged)
        self.horizontalScrollBar_MarketingImpact.valueChanged.connect(self.horizontalScrollBar_MarketingImpact_valueChanged)
        
        self.lineEdit_TaxRate.textChanged.connect(self.lineEdit_TaxRate_text_Changed)
        self.lineEdit_InterestRate.textChanged.connect(self.lineEdit_InterestRate_text_Changed)
        self.lineEdit_LoanLimit.textChanged.connect(self.lineEdit_LoanLimit_text_Changed)
        self.lineEdit_MaxPrice.textChanged.connect(self.lineEdit_MaxPrice_text_Changed)
        self.lineEdit_MaxMarketing.textChanged.connect(self.lineEdit_MaxMarketing_text_Changed)
        self.lineEdit_MaxCapInv.textChanged.connect(self.lineEdit_MaxCapInv_text_Changed)
        self.lineEdit_MaxRandD.textChanged.connect(self.lineEdit_MaxRandD_text_Changed)
        self.lineEdit_RandD.textChanged.connect(self.lineEdit_RandD_text_Changed)
        self.lineEdit_Price.textChanged.connect(self.lineEdit_Price_text_Changed)
        self.lineEdit_Marketing.textChanged.connect(self.lineEdit_Marketing_text_Changed)
        self.lineEdit_RandD.textChanged.connect(self.Max100)
        self.lineEdit_Price.textChanged.connect(self.Max100)
        self.lineEdit_Marketing.textChanged.connect(self.Max100)
        
        self.pushButton_ResetSettings.clicked.connect(self.pushButton_ResetSettings_was_clicked)
        
        
        if self.file["DemandChange"] >= 0:
            self.label_DemandChange_int.setText("+" + str(self.file["DemandChange"]) + "%")
        else:
            self.label_DemandChange_int.setText(str(self.file["DemandChange"]) + "%")
        
        if self.file["PriceImpact"] >= 0:
            self.label_PriceImpact_int.setText("+" + str(self.file["PriceImpact"]) + "%")
        else:
            self.label_PriceImpact_int.setText(str(self.file["PriceImpact"]) + "%")
            
        if self.file["RandDImpact"] >= 0:
            self.label_RandDImpact_int.setText("+" + str(self.file["RandDImpact"]) + "%")
        else:
            self.label_RandDImpact_int.setText(str(self.file["RandDImpact"]) + "%")
            
        if self.file["MarketingImpact"] >= 0:
            self.label_MarketingImpact_int.setText("+" + str(self.file["MarketingImpact"]) + "%")
        else:
            self.label_MarketingImpact_int.setText(str(self.file["MarketingImpact"]) + "%")
            
        self.lineEdit_TaxRate.setText(str(self.file["TaxRate"]))
        self.lineEdit_InterestRate.setText(str(self.file["InterestRate"]))
        self.lineEdit_LoanLimit.setText(str(self.file["LoanLimit"]))
        self.lineEdit_MaxPrice.setText(str(self.file["MaxPrice"]))
        self.lineEdit_MaxMarketing.setText(str(self.file["MaxMarketing"]))
        self.lineEdit_MaxCapInv.setText(str(self.file["MaxCapInv"]))
        self.lineEdit_MaxRandD.setText(str(self.file["MaxRandD"]))
        self.lineEdit_RandD.setText(str(self.file["RandD"]))
        self.lineEdit_Price.setText(str(self.file["Price"]))
        self.lineEdit_Marketing.setText(str(self.file["Marketing"]))
        QtCore.QMetaObject.connectSlotsByName(Dialog_setParameters)
        
        #game settings (made by Karton4ik)
        #self.data = {
        #    "DemandChange": 0,
        #    "RandDImpact": 0,
        #    "PriceImpact": 0,
        #    "MarketingImpact": 0,
        #    "TaxRate": 25,
        #    "InterestRate": 5,
        #    "LoanLimit": 30000,
        #    "MaxPrice": 99,
        #    "MaxMarketing": 15000,
        #    "MaxCapInv": 15000,
        #    "MaxRandD": 15000,
        #    "RandD": 30,
        #    "Price": 40,
        #    "Marketing": 30,
        #    
        #}
        
    def retranslateUi(self, Dialog_setParameters):
        _translate = QtCore.QCoreApplication.translate
        Dialog_setParameters.setWindowTitle(_translate("Dialog_setParameters", "Economic Parameters"))
        self.label_Sensitivity.setText(_translate("Dialog_setParameters", "Sensitivity"))
        self.label_DemandChange.setText(_translate("Dialog_setParameters", "Demand Change"))
        self.label_DemandChange_int.setText(_translate("Dialog_setParameters", "+0%"))
        self.label_PriceImpact_int.setText(_translate("Dialog_setParameters", "+0%"))
        self.label_PriceImpact.setText(_translate("Dialog_setParameters", "Price Impact"))
        self.label_RandDImpact_int.setText(_translate("Dialog_setParameters", "+0%"))
        self.label_RandDImpact.setText(_translate("Dialog_setParameters", "R and D Impact"))
        self.label_MarketingImpact_int.setText(_translate("Dialog_setParameters", "+0%"))
        self.label_MarketingImpact.setText(_translate("Dialog_setParameters", "Marketing Impact"))
        self.label_General.setText(_translate("Dialog_setParameters", "General"))
        self.label_TaxRate.setText(_translate("Dialog_setParameters", "Tax Rate"))
        self.lineEdit_TaxRate.setText(_translate("Dialog_setParameters", "25"))
        self.label_TaxRate_unit.setText(_translate("Dialog_setParameters", "%"))
        self.label_InterestRate.setText(_translate("Dialog_setParameters", "Interest Rate"))
        self.label_InterestRate_unit.setText(_translate("Dialog_setParameters", "%"))
        self.lineEdit_InterestRate.setText(_translate("Dialog_setParameters", "5"))
        self.label_LoanLimit.setText(_translate("Dialog_setParameters", "Loan Limit"))
        self.label_LoanLimit_unit.setText(_translate("Dialog_setParameters", "$"))
        self.lineEdit_LoanLimit.setText(_translate("Dialog_setParameters", "30000"))
        self.label_MaxPrice.setText(_translate("Dialog_setParameters", "Max. Price"))
        self.label_MaxPrice_unit.setText(_translate("Dialog_setParameters", "$"))
        self.lineEdit_MaxPrice.setText(_translate("Dialog_setParameters", "99"))
        self.label_MaxMarketing.setText(_translate("Dialog_setParameters", "Max. Marketing"))
        self.label_MaxMarketing_unit.setText(_translate("Dialog_setParameters", "$"))
        self.lineEdit_MaxMarketing.setText(_translate("Dialog_setParameters", "15000"))
        self.label_MaxCapInv.setText(_translate("Dialog_setParameters", "Max. Cap. Inv."))
        self.label_MaxCapInv_unit.setText(_translate("Dialog_setParameters", "$"))
        self.lineEdit_MaxCapInv.setText(_translate("Dialog_setParameters", "15000"))
        self.label_MaxRandD.setText(_translate("Dialog_setParameters", "Max. R and D"))
        self.label_MaxRandD_unit.setText(_translate("Dialog_setParameters", "$"))
        self.lineEdit_MaxRandD.setText(_translate("Dialog_setParameters", "15000"))
        self.label_RandD_unit.setText(_translate("Dialog_setParameters", "%"))
        self.label_Price_unit.setText(_translate("Dialog_setParameters", "%"))
        self.label_Marketing.setText(_translate("Dialog_setParameters", "Marketing"))
        self.label_Price.setText(_translate("Dialog_setParameters", "Price"))
        self.label_Marketing_unit.setText(_translate("Dialog_setParameters", "%"))
        self.label_RandD.setText(_translate("Dialog_setParameters", "R and D"))
        self.lineEdit_RandD.setText(_translate("Dialog_setParameters", "30"))
        self.lineEdit_Price.setText(_translate("Dialog_setParameters", "40"))
        self.lineEdit_Marketing.setText(_translate("Dialog_setParameters", "30"))
        self.label_MarketShare.setText(_translate("Dialog_setParameters", "Market Share"))
        self.pushButton_ResetSettings.setToolTip(_translate("Dialog_setParameters", "Return default settings"))
        self.pushButton_ResetSettings.setText(_translate("Dialog_setParameters", "Reset settings"))
        self.label_MAX100.setText(_translate("label_MAX100", "Max 100%"))


    def horizontalScrollBar_DemandChange_valueChanged(self, i):
        if i >= 0:
            self.label_DemandChange_int.setText(f"+{i}%")
        else:
            self.label_DemandChange_int.setText(f"{i}%")
        self.file["DemandChange"] = int(i)
           
    def horizontalScrollBar_RandDImpact_valueChanged(self, i):
        if i >= 0:
            self.label_RandDImpact_int.setText(f"+{i}%")
        else:
            self.label_RandDImpact_int.setText(f"{i}%")
        self.file["RandDImpact"] = int(i)
           
    def horizontalScrollBar_PriceImpact_valueChanged(self, i):
        if i >= 0:
            self.label_PriceImpact_int.setText(f"+{i}%")
        else:
            self.label_PriceImpact_int.setText(f"{i}%")
        self.file["PriceImpact"] = int(i)
                  
    def horizontalScrollBar_MarketingImpact_valueChanged(self, i):
        if i >= 0:
            self.label_MarketingImpact_int.setText(f"+{i}%")
        else:
            self.label_MarketingImpact_int.setText(f"{i}%")   
        self.file["MarketingImpact"] = int(i)
        
        
    def lineEdit_TaxRate_text_Changed(self, i):
        if i == '':
            i = 0
            
        self.file["TaxRate"] = int(i)

    def lineEdit_InterestRate_text_Changed(self, i):
        if i == '':
            i = 0
            
        self.file["InterestRate"] = int(i)
    
    def lineEdit_LoanLimit_text_Changed(self, i):
        if i == '':
            i = 0
            
        self.file["LoanLimit"] = int(i)
    
    def lineEdit_MaxPrice_text_Changed(self, i):
        if i == '':
            i = 0
            
        self.file["MaxPrice"] = int(i)
    
    def lineEdit_MaxMarketing_text_Changed(self, i):
        if i == '':
            i = 0
            
        self.file["MaxMarketing"] = int(i)
    
    def lineEdit_MaxCapInv_text_Changed(self, i):
        if i == '':
            i = 0
            
        self.file["MaxCapInv"] = int(i)
    
    def lineEdit_MaxRandD_text_Changed(self, i):
        if i == '':
            i = 0
            
        self.file["MaxRandD"] = int(i)
    
    def lineEdit_RandD_text_Changed(self, i):
        if i == '':
            i = 0
            
        self.file["RandD"] = int(i)
    
    def lineEdit_Price_text_Changed(self, i):
        if i == '':
            i = 0
            
        self.file["Price"] = int(i)
    
    def lineEdit_Marketing_text_Changed(self, i):
        if i == '':
            i = 0
            
        self.file["Marketing"] = int(i)
        
    def pushButton_ResetSettings_was_clicked(self):
        self.label_DemandChange_int.setText("+0%")
        self.label_PriceImpact_int.setText("+0%")
        self.label_RandDImpact_int.setText("+0%")
        self.label_MarketingImpact_int.setText("+0%")
        self.lineEdit_TaxRate.setText("25")
        self.lineEdit_InterestRate.setText("5")
        self.lineEdit_LoanLimit.setText("50000")
        self.lineEdit_MaxPrice.setText("99")
        self.lineEdit_MaxMarketing.setText("15000")
        self.lineEdit_MaxCapInv.setText("15000")
        self.lineEdit_MaxRandD.setText("15000")
        self.lineEdit_RandD.setText("30")
        self.lineEdit_Price.setText("40")
        self.lineEdit_Marketing.setText("30")
        
        
        
        #f = open("settings.txt", "w")
        data = {
            "DemandChange": 0,
            "RandDImpact": 0,
            "PriceImpact": 0,
            "MarketingImpact": 0,
            "TaxRate": 25,
            "InterestRate": 5,
            "LoanLimit": 50000,
            "MaxPrice": 99,
            "MaxMarketing": 15000,
            "MaxCapInv": 15000,
            "MaxRandD": 15000,
            "RandD": 30,
            "Price": 40,
            "Marketing": 30,
            
        }
        
        #f.write(str(data))
        self.file = data
        self.horizontalScrollBar_DemandChange.setSliderPosition(0)
        self.horizontalScrollBar_RandDImpact.setSliderPosition(0)
        self.horizontalScrollBar_PriceImpact.setSliderPosition(0)
        self.horizontalScrollBar_MarketingImpact.setSliderPosition(0)
    
    def Max100(self):
        def zero(i):
            if i == "":
                return 0
            else:
                return i
        if int(zero(self.file["RandD"])) + int(zero(self.file["Price"])) + int(zero(self.file["Marketing"])) > 100:
            self.label_MAX100.setStyleSheet("color: red;")
            self.buttonBox.setEnabled(False)
        else:
            self.label_MAX100.setStyleSheet("color: dark;")
            self.buttonBox.setEnabled(True)
    
    def save_was_clicked(self):
        f    = open("settings.txt", "w")
        f.write(str(self.file))
        f.close()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_setParameters = QtWidgets.QDialog()
    ui = Ui_Dialog_setParameters()
    ui.setupUi(Dialog_setParameters)
    Dialog_setParameters.show()
    sys.exit(app.exec())
